### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'Config' of undefined

### ISSUE THREAD

**Issue by raks-patel** [SpoonX/aurelia-config#15]
Hi!

I'm following your docs to configure the aurelia-forms plugin and i'm getting the above error.  I'm using the aurelia-api plugin as well but that is configured in the standard way. I'm not sure how to resolve this or figure out what the problem may be.  I've attached the bundled files for your convenience.

Thanks in advance!

```
import {Aurelia} from 'aurelia-framework'
import environment from './environment';
import * as entities from './config/entities';
import {Config} from 'aurelia-config';
import formConfig from './config/form';

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature('resources')
    .plugin('aurelia-config', configure => {
      return configure([
        'aurelia-form'
        // Other plugins
      ], formConfig);
    })
    .plugin('aurelia-api', config => {
      config.registerEndpoint('github', 'https://api.github.com/');
      config.registerEndpoint('bb-api', 'http://localhost:3000/api/', {headers: {'Content-Type': 'application/json; charset=utf-8'}});, 
      config.setDefaultEndpoint('bb-api');
    })
    // Register the plugin, and register our entities.
    .plugin('aurelia-orm', builder => {
      builder.registerEntities(entities);
    })
    .plugin('aurelia-validation');    

  if (environment.debug) {
    aurelia.use.developmentLogging();
  }

  if (environment.testing) {
    aurelia.use.plugin('aurelia-testing');
  }

  aurelia.start().then(() => aurelia.setRoot());
}
```

The formConfig is defined as follows:
```
export default {
  'aurelia-form': {
    // The default element used, probably best left unchanged
    defaultElement: 'input',

    // The default behavior to use for forms
    defaultBehavior: 'regular',

    // Register your (custom) elements here
    elements      : {},

    // Configured by aurelia-form-validation
    validation    : {},

    // Submit button configuration for <aurelia-form /> and <entity-form />
    submitButton: {
      enabled: true,        // Show the button
      options: ['primary'], // Options to pass to the button
      label  : 'Submit'     // Default (fallback) label of the button
    },

    // Alias these entity types to elements (used by aurelia-orm)
    aliases: {
      enum   : 'radio',
      int    : 'input',
      integer: 'input',
      number : 'input',
      float  : 'input',
      string : 'input',
      bool   : 'checkbox',
      boolean: 'checkbox',
      text   : 'textarea'
    }
  }
};
```

Error:
```
Unhandled rejection TypeError: Cannot read property 'Config' of undefined
    at Object.configure (http://localhost:9000/scripts/vendor-bundle.js:30677:46)
    at http://localhost:9000/scripts/vendor-bundle.js:12811:36
From previous event:
    at _loadPlugin (http://localhost:9000/scripts/vendor-bundle.js:12809:42)
    at http://localhost:9000/scripts/vendor-bundle.js:12802:16
From previous event:
    at loadPlugin (http://localhost:9000/scripts/vendor-bundle.js:12801:75)
    at next (http://localhost:9000/scripts/vendor-bundle.js:13063:20)
From previous event:
    at next (http://localhost:9000/scripts/vendor-bundle.js:13063:56)
    at http://localhost:9000/scripts/vendor-bundle.js:13070:16
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:13055:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:12671:39)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:74:17)
    at http://localhost:9000/scripts/vendor-bundle.js:11572:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:11567:56)
    at http://localhost:9000/scripts/vendor-bundle.js:11603:14
From previous event:
    at bootstrap (http://localhost:9000/scripts/vendor-bundle.js:11602:26)
    at http://localhost:9000/scripts/vendor-bundle.js:11589:9
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:11584:61)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:11609:37)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5480:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:4667:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4960:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5341:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4945:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3918:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3843:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4897:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4572:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5244:36
printWarning @ vendor-bundle.js:1395
formatAndLogError @ vendor-bundle.js:1111
fireRejectionEvent @ vendor-bundle.js:1136
Promise._notifyUnhandledRejection @ vendor-bundle.js:582
(anonymous) @ vendor-bundle.js:132
setTimeout (async)
(anonymous) @ vendor-bundle.js:131
Promise.resolve (async)
18../util @ vendor-bundle.js:3155
s @ vendor-bundle.js:30
(anonymous) @ vendor-bundle.js:30
1../queue @ vendor-bundle.js:34
s @ vendor-bundle.js:30
(anonymous) @ vendor-bundle.js:30
module.exports @ vendor-bundle.js:2146
3../promise @ vendor-bundle.js:271
s @ vendor-bundle.js:30
e @ vendor-bundle.js:30
(anonymous) @ vendor-bundle.js:30
(anonymous) @ vendor-bundle.js:30
(anonymous) @ vendor-bundle.js:30
```
[src.zip](https://github.com/SpoonX/aurelia-config/files/915556/src.zip)

**Comment by RWOverdijk** [comment]
First off, excellent issue! All the info I might need, including source code included. Well done :)

I'll take a look at this somewhere today, I'll let you know what I find.

**Comment by RWOverdijk** [comment]
Sorry, one more thing, I'd like to be able to build this. I need to find the line of code responsible. Could you include that for me? Then I know where it tries to access Config

**Comment by raks-patel** [comment]
Hey!

I've attached the source so you can build it.  I'm using VSCode as the editor if that helps at all.  Many thanks.

[testaurelia.zip](https://github.com/SpoonX/aurelia-config/files/915788/testaurelia.zip)

**Comment by RWOverdijk** [comment]
@raks-patel I think you need to either install `aurelia-view-manager` or register it:

```js
aurelia.use.plugin('aurelia-config', config => config([
  'aurelia-form',
  'aurelia-form-validation',
  'aurelia-view-manager'
], mergedConfig));
```

aurelia-config can configure many plugins by the way (if they offer support) including api. example:


```js
aurelia.use.plugin('aurelia-config', config => config([
  'aurelia-autocomplete',
  'aurelia-api',
  'aurelia-authentication',
  'aurelia-datatable',
  'aurelia-form',
  'aurelia-form-validation',
  'aurelia-dialog',
  'aurelia-filter',
  'aurelia-notification',
  'aurelia-view-manager'
], mergedConfig));
```

**Comment by raks-patel** [comment]
@RWOverdijk : Thanks for such a fast response! That fixed the issue i was having 👍

**Comment by RWOverdijk** [comment]
No problem! Glad it's resolved :)

In the future, you can also find us in the [chat on gitter](https://gitter.im/spoonx/dev).

**Comment by raks-patel** [comment]
Ah great, i will next time :-)
